# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /

# Spring Configuration
spring:
  application:
    name: privsense
  jackson:
    default-property-inclusion: NON_NULL
  # Cache Configuration
  cache:
    type: caffeine
    cache-names: tableMetadata,columnMetadata,relationshipMetadata,tableResults,columnResults,piiResults
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=60m

# PrivSense Configuration
privsense:
  # PII Detection Configuration
  pii-detection:
    # NER Service Configuration
    ner-service:
      url: http://localhost:5000/ner
      timeout: 10000
      max-request-size: 100KB
      trust-all-certs: false
    
    # Detection Configuration
    detection:
      confidence-threshold: 0.7
      sampling-limit: 10
      batch-size: 20
      enable-cache: true
  
  # Database Scanner Configuration
  database:
    # Scanner Configuration
    scanner:
      cache-ttl: 60m
      max-tables: 1000
      schema-filter: public
      include-views: true
    
    # Driver Management
    drivers:
      directory: ${user.home}/.privsense/drivers
      repository-url: https://repo1.maven.org/maven2
      coordinates:
        oracle.jdbc.OracleDriver: com.oracle.database.jdbc:ojdbc8:23.3.0
        com.mysql.cj.jdbc.Driver: mysql:mysql-connector-java:8.0.33
        org.postgresql.Driver: org.postgresql:postgresql:42.7.1
    
    # Connection Pool Configuration
    connection-pool:
      max-size: 10
      min-idle: 2
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
    
    # Sampling Configuration  
    sampling:
      default-size: 100
      max-size: 10000
      timeout: 30
      timeout-unit: SECONDS
      use-reservoir-for-large-tables: true
      reservoir-threshold: 10000
    
    # Task Processing
    tasks:
      queue-capacity: 1000
      batch-size: 20
      poll-timeout: 500
      poll-timeout-unit: MILLISECONDS
      thread-pool-size: 8
      sampler-pool-size: 4
      sampling-consumers: 3
      
# Logging Configuration
logging:
  level:
    root: INFO
    com.cgi.privsense: INFO
    org.springframework: WARN
    com.zaxxer.hikari: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"