# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /

# Spring Configuration
spring:
  application:
    name: privsense
  jackson:
    default-property-inclusion: NON_NULL
  # Cache Configuration
  cache:
    type: caffeine
    cache-names: tableMetadata,columnMetadata,relationshipMetadata,tableResults,columnResults,piiResults
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=60m

# Root level properties for backward compatibility
piidetector:
  ner:
    service:
      url: ${privsense.piiDetector.ner.service.url}
    trust:
      all:
        certs: ${privsense.piiDetector.ner.trust.all.certs}

# PrivSense Global Configuration
privsense:
  piiDetector:
    confidence:
      threshold: 0.7
    sampling:
      limit: 10
    ner:
      service:
        url: http://localhost:5000/ner
      trust:
        all:
          certs: false

  # Database Scanner Configuration
  dbScanner:
    # Drivers configuration
    drivers:
      directory: ${user.home}/.dbscanner/drivers
      repository-url: https://repo1.maven.org/maven2
      coordinates:
        oracle.jdbc.OracleDriver: com.oracle.database.jdbc:ojdbc8:23.3.0
        com.mysql.cj.jdbc.Driver: mysql:mysql-connector-java:8.0.33
        org.postgresql.Driver: org.postgresql:postgresql:42.7.1

    # Queue configuration
    queue:
      capacity: 1000
      batch-size: 20
      poll-timeout: 500
      poll-timeout-unit: MILLISECONDS

    # Threads configuration
    threads:
      max-pool-size: 8
      sampler-pool-size: 4
      sampling-consumers: 3

    # Sampling configuration
    sampling:
      timeout: 30
      timeout-unit: SECONDS
      use-queue: true
      default-sample-size: 100
      max-sample-size: 10000

    # Connection pool configuration
    connectionPool:
      default-max-pool-size: 10
      default-min-idle: 2
      default-connection-timeout: 30000
      default-idle-timeout: 60000
      default-max-lifetime: 1800000
      default-leak-detection-threshold: 60000

# Logging and other configuration remains the same